#!/usr/bin/env python
# coding: utf-8

import os
import sys

# Local import
DIR_PWD = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(DIR_PWD, ".."))
from linuxiso.scripts.customcli import argument_parser, main  # noqa


if __name__ == "__main__":
    """Entry point for command ligne usage (with options/arguments)"""
    parser = argument_parser()
    args = parser.parse_args()
    main(args)

# TODO: option s create and context
#
# class CreateAction(argparse.Action):
#     def __call__(self, parser, namespace, values, option_string=None):
#         if len(namespace.passwords) < len(namespace.users):
#             parser.error('Missing context')
#         else:
#             namespace.users.append(values)
#
#
# class ContextAction(argparse.Action):
#     def __call__(self, parser, namespace, values, option_string=None):
#         if len(namespace.users) <= len(namespace.passwords):
#             parser.error('Missing iso (create)')
#         else:
#             namespace.passwords.append(values)
#
#
# parser = argparse.ArgumentParser()
#
# parser.add_argument('--user', dest='users', default=[], action=UserAction, required=True)
#
# print(parser.parse_args())
