#!/usr/bin/env python
# coding: utf-8

import os
import sys

# Local import
DIR_PWD = os.path.dirname(os.path.realpath('__file__'))
sys.path.append(os.path.join(DIR_PWD, ".."))
from linuxiso.scripts.downloadcli import argument_parser, main  # noqa




if __name__ == "__main__":
    """Entry point for command ligne usage (with options/arguments)"""
    parser = argument_parser()
    args = parser.parse_args()
    main(args)
