#!/usr/bin/env python
# coding: utf-8

import os
import sys


# Local import
DIR_PWD = os.path.dirname(os.path.realpath('__file__'))
sys.path.append(os.path.join(DIR_PWD, ".."))
from linuxiso.scripts.virtualboxcli import argument_parser, main  # noqa


if __name__ == "__main__":
    """Entry point for command ligne usage (with options/arguments)"""

    parser = argument_parser()
    args = parser.parse_args()
    main(args)


    #  Exemple of comand ligne call:
    #   python virtualbox.py -l
    #   python virtualbox.py -c testdeploy -e Debian-amd64-standard -i /home/jnaud/var/isocustom/Custom-FullAuto-Debian-9-strech-amd64-netinst-server.iso
    #   python virtualbox.py -r testdeploy

    #   python virtualbox.py -c proliant -e Debian-amd64-raid -i /home/jnaud/var/isocustom/Custom-FullAuto-Debian-9-strech-amd64-netinst-server-proliant.iso

    # python virtualbox.py -c ubuntutest -e Debian-amd64-standard -i /home/jnaud/var/isocustom/Custom-FullAuto-Ubuntu-16.04.4-LTS-Xenial_Xerus-amd64-desktop.iso
    # python virtualbox.py -c ubuntutest -e Debian-amd64-standard -i /home/jnaud/var/isocustom/Custom-FullAuto-Ubuntu-17-Artful_Aardvark-amd64-desktop.iso
